sudo: false
language: node_js
node_js:
  - 6
  - 8
  - 10
  - 11

os:
  - linux
  - windows

script:
  - npm run lint
  - npm run test
  - npm run coverage -- --upload

addons:
  firefox: 'latest'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
