sudo: false
language: node_js
node_js:
  - 6
  - 8
  - 10
  - 11

os:
  - linux
  - windows

script:
  - npm run lint
  - npx nyc -s npm run test

after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

addons:
  firefox: 'latest'
